env:
  browser: true
  es2021: true

extends: 
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - functional

rules:
  react/react-in-jsx-scope: 0
  functional/functional-parameters: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  no-console: 0